"""Webhook Dispatcher — event delivery with HMAC signing and retry logic.

Provides a robust webhook dispatcher for delivering PGBank events to subscriber
URLs with configurable retries, HMAC signing, and delivery history.

Example:
    >>> from datetime import datetime, timezone, timedelta
    >>> from pgbank_unofficial import Event, Subscription, WebhookDispatcher
    >>> dispatcher = WebhookDispatcher()
    >>> dispatcher.add_subscription(Subscription(
    ...     url="https://my-app.com/webhooks/pgbank",
    ...     secret="my-hmac-secret",
    ...     event_types=["transaction.created"],
    ...     retry_attempts=3,
    ... ))
    >>> event = Event(
    ...     type="transaction.created",
    ...     timestamp=datetime.now(timezone.utc),
    ...     data={"amount": "500000", "account": "123456"},
    ... )
    >>> records = dispatcher.dispatch_sync(event)
    >>> print(f"Delivered to {len(records)} subscribers")
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from threading import Lock
from typing import Any, Callable, Optional

import httpx

logger = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# HMAC helpers
# ──────────────────────────────────────────────────────────────────────────────


def _sign_payload(payload: bytes, secret: str) -> str:
    """Return the HMAC-SHA256 hex digest of *payload* using *secret*.

    The signature is sent in the ``X-PGBank-Signature`` header.
    """
    return hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()


def _should_retry(status_code: int) -> bool:
    """Return True for status codes that should be retried."""
    # 5xx server errors — retry
    # 429 Too Many Requests — retry
    # 4xx client errors (except 429) — do NOT retry
    return status_code >= 500 or status_code == 429


def _discord_formatter(event: Event) -> dict:
    """Format an event for Discord webhook embedding."""
    fields = []
    for k, v in event.data.items():
        fields.append({"name": str(k), "value": str(v), "inline": True})

    color = 3447003  # Blue
    if "changed" in event.type or "created" in event.type:
        color = 3066993  # Green
    elif "paused" in event.type or "failed" in event.type:
        color = 15158332  # Red

    return {
        "embeds": [
            {
                "title": f"PGBank Event: {event.type}",
                "description": f"Event ID: `{event.id}`",
                "color": color,
                "fields": fields,
                "timestamp": event.timestamp.isoformat(),
            }
        ]
    }


def _make_telegram_formatter(
    chat_id: str, template: Optional[str] = None
) -> Callable[[Event], dict]:
    """Create a formatter for Telegram sendMessage endpoint with optional Jinja2 support."""
    default_template = (
        "🔔 <b>PGBank Event: {{ type }}</b>\n"
        "Time: {{ timestamp }}\n"
        "Data:\n"
        "{% for k, v in data.items() %}"
        "• <b>{{ k }}</b>: {{ v }}\n"
        "{% endfor %}"
    )
    tmpl_str = template or default_template

    def formatter(event: Event) -> dict:
        try:
            import jinja2

            env = jinja2.Environment()
            tmpl = env.from_string(tmpl_str)
            text = tmpl.render(
                type=event.type,
                timestamp=event.timestamp.isoformat(),
                data=event.data,
                id=event.id,
            )
        except ImportError:
            text = f"🔔 PGBank Event: {event.type}\nTime: {event.timestamp}\nData:\n"
            for k, v in event.data.items():
                text += f"- {k}: {v}\n"

        return {"chat_id": chat_id, "text": text, "parse_mode": "HTML"}

    return formatter


# ──────────────────────────────────────────────────────────────────────────────
# Event
# ──────────────────────────────────────────────────────────────────────────────


@dataclass
class Event:
    """A webhook event emitted by the library.

    Attributes:
        type: Event type identifier (e.g. ``"transaction.created"``).
        timestamp: When the event occurred.
        data: Arbitrary event payload (must be JSON-serializable).
        id: Unique event identifier (auto-generated by default).
    """

    type: str
    timestamp: datetime
    data: dict[str, Any]
    id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def to_json_bytes(self) -> bytes:
        """Serialize the event to JSON bytes (for HMAC signing)."""
        return json.dumps(
            {"type": self.type, "data": self.data, "id": self.id}, sort_keys=True
        ).encode()


# ──────────────────────────────────────────────────────────────────────────────
# Subscription
# ──────────────────────────────────────────────────────────────────────────────


@dataclass
class Subscription:
    """A webhook subscriber endpoint.

    Attributes:
        url: The HTTPS URL to deliver events to.
        secret: Optional HMAC secret for signing payloads.
        event_types: List of event types to receive (None = all events).
        headers: Extra HTTP headers to send with every request.
        timeout: Request timeout in seconds.
        retry_attempts: Number of delivery attempts (1 = no retry).
        retry_backoff: Exponential base for backoff delay (delay = backoff^attempt seconds).
        active: Whether the subscription is active.
    """

    url: str
    secret: Optional[str] = None
    event_types: Optional[list[str]] = None
    headers: dict[str, str] = field(default_factory=dict)
    timeout: float = 10.0
    retry_attempts: int = 3
    retry_backoff: float = 2.0
    active: bool = True
    formatter: Optional[Callable[[Event], dict]] = None


# ──────────────────────────────────────────────────────────────────────────────
# DeliveryRecord
# ──────────────────────────────────────────────────────────────────────────────


@dataclass
class DeliveryRecord:
    """Record of a single webhook delivery attempt (or multi-attempt retry cycle).

    Attributes:
        subscription_url: Target URL of the subscription.
        event_id: ID of the delivered event.
        event_type: Type of the delivered event.
        started_at: When delivery started.
        finished_at: When delivery completed.
        success: Whether the final attempt succeeded.
        status_code: HTTP status code (None if connection error).
        response: Response body text (truncated to 500 chars).
        error: Error message if failure.
        attempts: Number of delivery attempts made.
    """

    subscription_url: str
    event_id: str
    event_type: str
    started_at: datetime
    finished_at: Optional[datetime]
    success: bool
    status_code: Optional[int]
    response: Optional[str]
    error: Optional[str]
    attempts: int

    @property
    def duration(self) -> Optional[timedelta]:
        """Elapsed time of the delivery cycle."""
        if self.finished_at is None:
            return None
        return self.finished_at - self.started_at


# ──────────────────────────────────────────────────────────────────────────────
# WebhookDispatcher
# ──────────────────────────────────────────────────────────────────────────────


class WebhookDispatcher:
    """Dispatches :class:`Event` objects to registered webhook subscribers.

    Features:
        - HMAC-SHA256 payload signing (optional per-subscription)
        - Exponential backoff retry (configurable per-subscription)
        - In-memory delivery history (last 1000 records per dispatcher)
        - Sync delivery via ``dispatch_sync()``; async via ``dispatch()``
        - Subscription management: add, remove, pause, resume

    Args:
        max_concurrent_deliveries: Max simultaneous HTTP requests (default 4).
        http_client: Optional shared ``httpx.Client`` instance. If not provided,
            one is created on first use and closed on ``stop()``.
    """

    def __init__(
        self,
        *,
        max_concurrent_deliveries: int = 4,
        http_client: Optional[httpx.Client] = None,
    ) -> None:
        self._max_concurrent_deliveries = max(1, int(max_concurrent_deliveries))
        self._http_client = http_client
        self._owns_client = http_client is None
        self._subscriptions: dict[str, Subscription] = {}
        self._sub_ids: dict[str, str] = {}  # url -> id
        self._history: deque[DeliveryRecord] = deque(maxlen=1000)
        self._lock = Lock()
        self._started = False

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Start the dispatcher (create HTTP client if needed)."""
        if self._started:
            return
        if self._owns_client and self._http_client is None:
            self._http_client = httpx.Client(timeout=30.0)
        self._started = True
        logger.info("WebhookDispatcher started")

    def stop(self) -> None:
        """Stop the dispatcher and close the HTTP client."""
        if not self._started:
            return
        self._started = False
        if self._owns_client and self._http_client is not None:
            self._http_client.close()
            self._http_client = None
        logger.info("WebhookDispatcher stopped")

    def __enter__(self) -> "WebhookDispatcher":
        self.start()
        return self

    def __exit__(self, *_: Any) -> None:
        self.stop()

    # ── Subscription management ──────────────────────────────────────────────

    def add_subscription(self, subscription: Subscription) -> str:
        """Register a webhook subscription. Returns the subscription ID."""
        with self._lock:
            sub_id = str(uuid.uuid4())
            self._subscriptions[sub_id] = subscription
            self._sub_ids[subscription.url] = sub_id
        logger.info("Added subscription %s -> %s", sub_id, subscription.url)
        return sub_id

    def remove_subscription(self, sub_id: str) -> None:
        """Remove a subscription by ID. Raises KeyError if not found."""
        with self._lock:
            if sub_id not in self._subscriptions:
                raise KeyError(f"No subscription with id {sub_id}")
            url = self._subscriptions[sub_id].url
            del self._subscriptions[sub_id]
            del self._sub_ids[url]
        logger.info("Removed subscription %s", sub_id)

    def list_subscriptions(self) -> list[Subscription]:
        """Return a snapshot of all subscriptions."""
        with self._lock:
            return list(self._subscriptions.values())

    def pause_subscription(self, sub_id: str) -> None:
        """Pause a subscription (active=False)."""
        with self._lock:
            self._subscriptions[sub_id].active = False
        logger.info("Paused subscription %s", sub_id)

    def resume_subscription(self, sub_id: str) -> None:
        """Resume a paused subscription (active=True)."""
        with self._lock:
            self._subscriptions[sub_id].active = True
        logger.info("Resumed subscription %s", sub_id)

    def register_discord(self, webhook_url: str, *, events: Optional[list[str]] = None) -> str:
        """Register a Discord webhook subscription. Returns the subscription ID."""
        sub = Subscription(
            url=webhook_url,
            event_types=events,
            formatter=_discord_formatter,
        )
        return self.add_subscription(sub)

    def register_telegram(
        self,
        bot_token: str,
        chat_id: str,
        *,
        events: Optional[list[str]] = None,
        template: Optional[str] = None,
    ) -> str:
        """Register a Telegram bot webhook subscription. Returns the subscription ID."""
        url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
        sub = Subscription(
            url=url,
            event_types=events,
            formatter=_make_telegram_formatter(chat_id, template),
        )
        return self.add_subscription(sub)

    def register_webhook(
        self,
        url: str,
        *,
        secret: Optional[str] = None,
        events: Optional[list[str]] = None,
        headers: Optional[dict[str, str]] = None,
    ) -> str:
        """Register a standard HTTP webhook subscription. Returns the subscription ID."""
        sub = Subscription(
            url=url,
            secret=secret,
            event_types=events,
            headers=headers or {},
        )
        return self.add_subscription(sub)

    # ── Delivery ─────────────────────────────────────────────────────────────

    def _matching_subscriptions(self, event: Event) -> list[Subscription]:
        """Return active subscriptions whose event_types filter accepts *event*.

        A subscription matches when:
          - ``active`` is True, AND
          - ``event_types`` is None (subscribe to all), OR
          - ``event.type`` is in ``event_types``.
        """
        with self._lock:
            subs = list(self._subscriptions.values())
        return [
            sub
            for sub in subs
            if sub.active and (sub.event_types is None or event.type in sub.event_types)
        ]

    def dispatch_sync(self, event: Event) -> list[DeliveryRecord]:
        """Deliver *event* synchronously to all matching active subscriptions.

        Returns a list of :class:`DeliveryRecord`, one per subscription that
        was attempted (inactive or filtered subscriptions are skipped).
        """
        return [
            self._deliver_to_subscription_sync(sub, event)
            for sub in self._matching_subscriptions(event)
        ]

    async def dispatch(self, event: Event) -> list[DeliveryRecord]:
        """Deliver *event* asynchronously to all matching active subscriptions."""
        import asyncio

        coros = [
            self._deliver_to_subscription_async(sub, event)
            for sub in self._matching_subscriptions(event)
        ]
        return await asyncio.gather(*coros)

    def get_delivery_history(self, *, sub_id: Optional[str] = None) -> list[DeliveryRecord]:
        """Return delivery history, optionally filtered by subscription ID."""
        with self._lock:
            records = list(self._history)
        if sub_id is not None:
            with self._lock:
                sub = self._subscriptions.get(sub_id)
            if sub is None:
                return []
            records = [r for r in records if r.subscription_url == sub.url]
        return records

    # ── Internal: sync delivery ───────────────────────────────────────────────

    def _deliver_to_subscription_sync(self, sub: Subscription, event: Event) -> DeliveryRecord:
        """Deliver an event to a single subscription (sync, with retries)."""
        started_at = datetime.now()
        if sub.formatter:
            payload_dict = sub.formatter(event)
            payload_bytes = json.dumps(payload_dict, default=str, sort_keys=True).encode()
        else:
            payload_bytes = event.to_json_bytes()
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "pgbank-unofficial-webhook/1.0",
            **sub.headers,
        }
        if sub.secret:
            headers["X-PGBank-Signature"] = _sign_payload(payload_bytes, sub.secret)

        # Event type filter — return a "skipped" record (not a failure)
        if sub.event_types is not None and event.type not in sub.event_types:
            return DeliveryRecord(
                subscription_url=sub.url,
                event_id=event.id,
                event_type=event.type,
                started_at=started_at,
                finished_at=started_at,
                success=True,
                status_code=None,
                response="skipped",
                error=None,
                attempts=0,
            )

        attempt = 0
        last_error: Optional[str] = None
        last_status: Optional[int] = None
        last_response: Optional[str] = None

        while attempt < sub.retry_attempts:
            attempt += 1
            try:
                # Use httpx.post() at module level so tests can mock it via
                # patch("pgbank_unofficial.webhook.httpx").
                response = httpx.post(
                    sub.url,
                    content=payload_bytes,
                    headers=headers,
                    timeout=sub.timeout,
                )
                last_status = response.status_code
                last_response = response.text[:500] if response.text else None

                if 200 <= response.status_code < 300:
                    finished_at = datetime.now()
                    record = DeliveryRecord(
                        subscription_url=sub.url,
                        event_id=event.id,
                        event_type=event.type,
                        started_at=started_at,
                        finished_at=finished_at,
                        success=True,
                        status_code=last_status,
                        response=last_response,
                        error=None,
                        attempts=attempt,
                    )
                    self._record_delivery(record)
                    return record

                if not _should_retry(last_status):
                    # Non-retryable: 4xx (except 429)
                    finished_at = datetime.now()
                    record = DeliveryRecord(
                        subscription_url=sub.url,
                        event_id=event.id,
                        event_type=event.type,
                        started_at=started_at,
                        finished_at=finished_at,
                        success=False,
                        status_code=last_status,
                        response=last_response,
                        error=f"HTTP {last_status} (non-retryable)",
                        attempts=attempt,
                    )
                    self._record_delivery(record)
                    return record

                # Retryable error: sleep and retry
                delay = min(sub.retry_backoff**attempt, 60.0)
                logger.warning(
                    "Webhook delivery to %s failed (attempt %d/%d, status %d). "
                    "Retrying in %.1fs.",
                    sub.url,
                    attempt,
                    sub.retry_attempts,
                    last_status,
                    delay,
                )
                time.sleep(delay)

            except Exception as exc:  # noqa: BLE001
                last_error = f"{type(exc).__name__}: {exc}"
                logger.warning(
                    "Webhook delivery to %s failed (attempt %d/%d): %s. Retrying.",
                    sub.url,
                    attempt,
                    sub.retry_attempts,
                    exc,
                )
                delay = min(sub.retry_backoff**attempt, 60.0)
                time.sleep(delay)

        # All retries exhausted
        finished_at = datetime.now()
        error_msg = last_error or f"HTTP {last_status} after {attempt} attempts"
        record = DeliveryRecord(
            subscription_url=sub.url,
            event_id=event.id,
            event_type=event.type,
            started_at=started_at,
            finished_at=finished_at,
            success=False,
            status_code=last_status,
            response=last_response,
            error=error_msg,
            attempts=attempt,
        )
        self._record_delivery(record)
        return record

    # ── Internal: async delivery ─────────────────────────────────────────────

    async def _deliver_to_subscription_async(
        self, sub: Subscription, event: Event
    ) -> DeliveryRecord:
        """Deliver an event to a single subscription (async, with retries)."""
        import asyncio

        import httpx as async_httpx

        started_at = datetime.now()
        if sub.formatter:
            payload_dict = sub.formatter(event)
            payload_bytes = json.dumps(payload_dict, default=str, sort_keys=True).encode()
        else:
            payload_bytes = event.to_json_bytes()
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "pgbank-unofficial-webhook/1.0",
            **sub.headers,
        }
        if sub.secret:
            headers["X-PGBank-Signature"] = _sign_payload(payload_bytes, sub.secret)

        # Event type filter
        if sub.event_types is not None and event.type not in sub.event_types:
            return DeliveryRecord(
                subscription_url=sub.url,
                event_id=event.id,
                event_type=event.type,
                started_at=started_at,
                finished_at=started_at,
                success=True,
                status_code=None,
                response="skipped",
                error=None,
                attempts=0,
            )

        attempt = 0
        last_error: Optional[str] = None
        last_status: Optional[int] = None
        last_response: Optional[str] = None

        async with async_httpx.AsyncClient(timeout=sub.timeout) as client:
            while attempt < sub.retry_attempts:
                attempt += 1
                try:
                    response = await client.post(sub.url, content=payload_bytes, headers=headers)
                    last_status = response.status_code
                    last_response = response.text[:500] if response.text else None

                    if 200 <= response.status_code < 300:
                        finished_at = datetime.now()
                        record = DeliveryRecord(
                            subscription_url=sub.url,
                            event_id=event.id,
                            event_type=event.type,
                            started_at=started_at,
                            finished_at=finished_at,
                            success=True,
                            status_code=last_status,
                            response=last_response,
                            error=None,
                            attempts=attempt,
                        )
                        self._record_delivery(record)
                        return record

                    if not _should_retry(last_status):
                        finished_at = datetime.now()
                        record = DeliveryRecord(
                            subscription_url=sub.url,
                            event_id=event.id,
                            event_type=event.type,
                            started_at=started_at,
                            finished_at=finished_at,
                            success=False,
                            status_code=last_status,
                            response=last_response,
                            error=f"HTTP {last_status} (non-retryable)",
                            attempts=attempt,
                        )
                        self._record_delivery(record)
                        return record

                    delay = min(sub.retry_backoff**attempt, 60.0)
                    logger.warning(
                        "Async webhook delivery to %s failed (attempt %d/%d, status %d). "
                        "Retrying in %.1fs.",
                        sub.url,
                        attempt,
                        sub.retry_attempts,
                        last_status,
                        delay,
                    )
                    await asyncio.sleep(delay)

                except Exception as exc:  # noqa: BLE001
                    last_error = f"{type(exc).__name__}: {exc}"
                    logger.warning(
                        "Async webhook delivery to %s failed (attempt %d/%d): %s. Retrying.",
                        sub.url,
                        attempt,
                        sub.retry_attempts,
                        exc,
                    )
                    delay = min(sub.retry_backoff**attempt, 60.0)
                    await asyncio.sleep(delay)

        finished_at = datetime.now()
        error_msg = last_error or f"HTTP {last_status} after {attempt} attempts"
        record = DeliveryRecord(
            subscription_url=sub.url,
            event_id=event.id,
            event_type=event.type,
            started_at=started_at,
            finished_at=finished_at,
            success=False,
            status_code=last_status,
            response=last_response,
            error=error_msg,
            attempts=attempt,
        )
        self._record_delivery(record)
        return record

    # ── Internal: history ────────────────────────────────────────────────────

    def _record_delivery(self, record: DeliveryRecord) -> None:
        """Append a delivery record to in-memory history."""
        with self._lock:
            self._history.append(record)


__all__ = [
    "Event",
    "Subscription",
    "DeliveryRecord",
    "WebhookDispatcher",
    "_sign_payload",
]
